databases:
  - name: urbanvista
    databaseName: urbanvista
    user: name_of_youurbanvistar_app
    plan: free

services:
  - type: web
    plan: free
    name: urbanvista
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urbanvista
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync:false- key: WEB_CONCURRENCY
        value: 2